spring:
  datasource:
    url: jdbc:mysql://lion-db.cdsmog4k8wo3.ap-northeast-2.rds.amazonaws.com:3306/mydatabase
    username: ${admin}
    password: ${test1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
